services:
  - type: web
    name: dog-api
    env: node
    buildCommand: |
      npm install
      npm run build
      cd dog-api-frontend
      npm install
      npm run build
      cd ..
    startCommand: npm start
    autoDeploy: true
    plan: free
    envVars:
      - key: MONGO_URI
        fromSecret: MONGO_URI
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
